In [1]:
import numpy as np 
import pandas as pd 
from sklearn import metrics

In [2]:
data_set= pd.read_csv('diabetes.csv') 
data_set

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
X= data_set.iloc[:, :-1].values 
 
Y= data_set.iloc[:, -1].values

In [4]:
from sklearn.model_selection import train_test_split 
X_train, X_test, Y_train,Y_test = train_test_split(X,Y,test_size = 
0.3,random_state= 99)

In [5]:
from sklearn import linear_model 
model = linear_model.LinearRegression() 
model.fit(X_train, Y_train) 
y_pred = model.predict(X_test) 
result = pd.DataFrame({'Actual': Y_test, 'Predict' : y_pred}) 
result

     Actual   Predict
0         1  0.217832
1         0  0.097034
2         0  0.062623
3         0  0.200074
4         1  0.056657
..      ...       ...
226       0  0.376765
227       1  0.795820
228       1  0.708049
229       0  0.376236
230       1  0.460767

[231 rows x 2 columns]

In [6]:
mse= metrics.mean_squared_error(Y_test, y_pred) 
print("Mean Squared Error:", mse)

Mean Squared Error: 0.15803739458360813

In [7]:
rmse= np.sqrt(mse) 
print("Root Mean Squared Error:", rmse)

Root Mean Squared Error: 0.3975391736465831

In [8]:
accuracy = model.score(X_test,Y_test)*100 
print("Accuracy: ",accuracy)

Accuracy:  28.412280030764727